FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock README.md ./
COPY src ./src
COPY alembic ./alembic
COPY alembic.ini ./

RUN uv sync --frozen

EXPOSE 8000

CMD ["uv", "run", "ganga-aqua", "runserver", "--host", "0.0.0.0", "--port", "8000"]
